# -*- coding: utf-8 -*-
"""data_generation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RK7krlImCJV0caXO-P2X9GpZqcgoUsgv
"""

!pip install praw

import praw 

reddit = praw.Reddit(client_id='cjIoq63O9RwBoKegJGnQ1g', client_secret='IzrhLPNi8vxHN0uakCW6fTNi42eBeQ', username='quierohelp', password='coolkid19980', user_agent='prawtutorialv1')

import csv
import re
from sklearn.model_selection import train_test_split
def get_data(size, flairs, csv_path):
  header = ['title', 'text', 'flair']
  data = [[1, 2, 3]]
  subreddit = reddit.subreddit('askscience')
  hot_posts = subreddit.hot(limit=size)
  i = 0; 
  for submissions in hot_posts:
    temp = [1,2,3]
    if(submissions.link_flair_text in flairs):
      temp[0] = submissions.title
      if(submissions.selftext == ""):
        temp[1] = submissions.title
      else:
        temp[1] = submissions.selftext
      temp[2] = submissions.link_flair_text
      data.insert(i, temp)
    i = i+1 
  data.pop(0)
  print(len(data))
  with open(csv_path, 'w', encoding='UTF8') as f:
    writer = csv.writer(f)
    # write the header
    writer.writerow(header)
    # write the data
    writer.writerows(data)

def to_fasttext(csv_path, txt_path, txt_path1):
  lines = ["test"]
  
  data = pd.read_csv(csv_path)
  
  y = data.iloc[:, len(data.iloc[0]) - 1]
  print(len(y))

  for i in range(len(y)):
    text = data.iloc[i][1]
    label = y[i]
    text = strip_formatting(text)

    s = '__label__{} {}'.format(label, text)
    lines.insert(i, s)
  lines.pop()

  train_data, test_data = train_test_split(lines, test_size=0.1, random_state=7)
  print("train_data", len(train_data))
  print("test_data", len(test_data))

  with open(txt_path, 'w') as f:
    for line in train_data:
      line = line.replace('\n', " ")
      f.write(line)
      f.write("\n")

  with open(txt_path1, 'w') as f:
    for line in test_data:
      line = line.replace('\n', " ")
      f.write(line)
      f.write("\n")


def strip_formatting(string):
    string = string.lower()
    string = re.sub(r"([.!?,'/()])", r" \1 ", string)
    return string


  
get_data(2000, ["Physics", "Astronomy", "Mathematics", "Computing", "Engineering", "Chemistry", "Earth Sciences", "Planetary Sci." , "Biology", "Paleontology"], "/content/drive/MyDrive/reddit/askscience.csv")
to_fasttext("/content/drive/MyDrive/reddit/askscience.csv", "/content/drive/MyDrive/reddit/fasttextdata.txt", "/content/drive/MyDrive/reddit/fasttextdatatest.txt")

